### PR TITLE
Add manual initialization Reaper example

### PR DESCRIPTION
**Pull request by chromy**

### CODE REVIEW

**Review by rbro112 — APPROVED** [review]
Looks great, one suggestion is to add a minimal readme explaining what is different about this vs. the standard sample and what specifically users need to do to manually initialize.

**Comment by chromy** [comment]
Added a readme!

**Comment by chromy** [comment]
Not sure about the root cause of the failure:
```
1920), focused=true, active=true, hasParent=false, isAnchored=false, hasChildren=false]
07-24 06:07:07.110  9536  9536 I Finsky  : [1] adul.onStartJob(128): SCH: job service start with id 9150.
07-24 06:07:07.110 10464 10488 E TestRunner: failed: navigateToDetailScreen(com.emergetools.reaper.sample.ReaperSampleUiTest)
07-24 06:07:07.110 10464 10488 E TestRunner: ----- begin exception -----
07-24 06:07:07.111 10464 10488 E TestRunner: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
07-24 06:07:07.111 10464 10488 E TestRunner: 	at com.emergetools.reaper.sample.ReaperSampleUiTest.navigateToDetailScreen(ReaperSampleUiTest.kt:48)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:111)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
07-24 06:07:07.111 10464 10488 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1977)
07-24 06:07:07.111 10464 10488 E TestRunner: ----- end exception -----
07-24 06:07:07.114 10464 10488 I TestRunner: finished: navigateToDetailScreen(com.emergetools.reaper.sample.ReaperSampleUiTest)
07-24 06:07:07.140  1037  1353 W AlarmManager: mIsScreenOn is: true, WAKEUP alarm talarm.operation == null,package name is: android listenerTag is: WifiConnectivityManager Schedule Periodic Scan Timer creator uid is: 1000```

going to try rerunning.

**Comment by chromy** [comment]
Looks like a flake :/

**Pull request merged**
